
try {
   test1();
} catch (error) {
    console.log(error.name);
    console.log(error.message)
}